### ISSUE TITLE
What about FileSafe?

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/snserver_ynh#26]
We have the standard notes server and web installed via ynh, but when I try to attach a file to a note, it asks me to setup FileSafe. https://standardnotes.com/filesafe - Why isn't it possible to simply attach files and have FileSafe use our server for storage? 

Else it redirects to https://filesafe.standardnotes.org/integrations/link?source=webdav and it is confusing.

**Comment by FabianWilkens** [comment]
Hey,

as far as I know it is not possible to safe files on your server.

But with the FileSafe function you can safe file on 3rd-party storage. I think before upload the files will be encrypted.

[https://github.com/standardnotes/filesafe-relay]()
>
This is the server component that is part of the larger FileSafe system. It deals with relaying files to the proper 3rd party storage provider, such as Dropbox, Google Drive, WebDAV, or AWS S3.

I haven't created an filesafe-relay package for YunoHost, because I think it is not needed.

**Comment by TROMsite** [comment]
I didn't even know about it until I tried to add a photo to my notes to then be sent to a completely new url that asks me to use amazon or google. At first I was surprised. We'd love to provide storage on the local server and I am surprised there is no such option. I am concerned that relying on a 3rd party for such a basic and needed function (to store files inside notes), is not a good practice. What if their filesafe changes or shuts down or idk...?

**Comment by TROMsite** [comment]
I submitted and issue here https://github.com/standardnotes/filesafe-relay/issues/39 and I saw here https://github.com/standardnotes/filesafe-relay/issues/33#issuecomment-847645443 that they are planning for just that! Which sounds really good ;)

**Comment by dumprop** [comment]
> I haven't created an filesafe-relay package for YunoHost, because I think it is not needed.

I think it could be helpful :)

**Comment by FabianWilkens** [comment]
New version is merged.

New users are getting a PRO subscription and file space (Default: 100MB) automatically.

**Comment by dumprop** [comment]
> New version is merged.
> 
> New users are getting a PRO subscription and file space (Default: 100MB) automatically.

![image](https://user-images.githubusercontent.com/34004367/185796355-58a25538-a261-4621-ac8c-e1ad691bc12c.png)
:(

**Comment by FabianWilkens** [comment]
Did you tried this with a new user or an user which already exist before the upgrade?

**Comment by drapado** [comment]
Same error as [dumprop comment](https://github.com/YunoHost-Apps/snserver_ynh/issues/26#issuecomment-1221558377):
```
Unable to start upload session
There was an error while uploading
```
In a clean install of yunohost and snserver with new users.

**Comment by FabianWilkens** [comment]
Can you give me some information

- Server Version
- Client Version
- Client platform (Web/Windows/Mobile/....)

**Comment by drapado** [comment]
Hi,
- Server: 3.39.1~ynh1
- Clients:
    - Desktop on linux (3.23.115) and windows (3.23.176)
    - Android (3.37.14)

**Comment by FabianWilkens** [comment]
I am not able to recreate the problem you are having when using the web or desktop client.
Can you show me the error message in the web console for the web or desktop client?


On the android app I am expierience the same problem, but with a different error message.
Try to figure that out.

**Comment by drapado** [comment]
Ok, so after reading the console I could solve the error on the web/desktop app myself. The problem was that along the process I change the domain name (after install), but the files server domain apparently didn't change. After re-installing the server, file upload works in web/desktop. However, as you mention, it does not work in android. Any ideas why?

Again, thanks for looking it up :)

**Comment by FabianWilkens** [comment]
Thats nice too hear.

No not yet.
But I saw that other selfhosters have the same problme with the android / ios app.

**Comment by drapado** [comment]
Interestingly, if you opt in for the "New mobile experience" in the android app, the file upload works
