### ISSUE TITLE
Adding Secure Spreadsheet to supported extensions

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/snserver_ynh#8]
Hello,

first thanks again for adding support for selfhosting the extensions.

Would you mind also adding the secure spreadsheet?

https://standardnotes.org/extensions/secure-spreadsheets

Thanks in advance
🤗

**Comment by FabianWilkens** [comment]
Hey,

I would, but unfortunately this extension has no license

**Comment by nr458h** [comment]
Thanks for the hint

I mad a [request](https://github.com/standardnotes/secure-spreadsheets/issues/41) to add the license.

Also on their website they say ...

> Standard Notes publishes the source code for its web, desktop, and mobile apps as well as its syncing server and extensions under AGPLv3. This means that any individual or company can legally use all our free and open-source software for their own commercial purposes and therefore potentially drive us out of business.

**Comment by brimwats** [comment]
Use this https://github.com/kylejbrk/standard-notes-open-extended

**Comment by nr458h** [comment]
Ok - I would prefere to self-host the extensions. Do you know how it is possible that the hole repository is licensed under GPL v3 https://github.com/kylejbrk/standard-notes-open-extended/blob/master/LICENSE

@FabianWilkens 
Any ideas how to continue with that?
The offical spread-sheet has no free license, I asked and one of the contributers said, they can not because there are dependencies to kendo ui core
But this repository is also licensed under a free license (Apache v2)

So what to do - or can we just like in the repository mentioned above add the spread-sheet to the extensions?
Thanks in advance

**Comment by FabianWilkens** [comment]
@nr458h 
I would like to add this extension.
I aksed around , but there is no way I can add it.
In the yunohost app catalog are only apps allow which are free.
And without an Licence file in the Github repository, I cant add this.

I have almost no knowledge of licences, but that is how I understand it.

**Comment by FabianWilkens** [comment]
New version is merged.

Selfhosted extensions are removed. And are now integrated in the client apps.
New users are getting a PRO subscription and file space (Default: 100MB) automatically.
